### ISSUE TITLE
Consider making macro-areas addressable by URL

### ISSUE THREAD

**Issue by mdingemanse** [clld/glottolog#175]
On http://glottolog.org/glottolog/language it's fairly easy to narrow down by selecting a macro-area, but the URL doesn't change along with the page updage, so the resulting page isn't easily linkable or shareable. It would be useful to be able to share a link like http://glottolog.org/glottolog/language/macro-area/africa .

**Comment by xflr6** [comment]
Thanks. I fully agree: it is a virtue of the web to have nice, shareable URLs for resources.
AFAIR, we use the [datatables](https://datatables.net) JavaScript library for all list-views in `clld`: It fills the table with data fetched in the background via [XHR](https://en.wikipedia.org/wiki/XMLHttpRequest) from special URL in the web-apps framework. This is why the main browser URL does not change when you browse or filter (just like in [single page webapps](https://en.wikipedia.org/wiki/Single-page_application)). What I am trying to illustrate is that it would probably take considerable effort to change our list-view interface to use classic full-page loads with dedicated urls/parameters for all or most filters: On the other hand, datatables provides a lot of functionality for us (not sure if there might be a hacky way to emulate this for this case with JavaScript and/or redirects though).

**Comment by xrotwang** [comment]
@mdingemanse what you can do right now is the following: On http://glottolog.org/glottolog/language select the macro-area you are interested in, and then chose the `map.html` download (from the download dropdown menu on the top right of the table). This will load a map and list of languages respecting the current selection in the table:
http://glottolog.org/glottolog/language.map.html?type=languages&sEcho=1&iSortingCols=1&iSortCol_0=0&sSortDir_0=asc&sSearch_4=1

The resulting URL - admittedly - is rather opaque and ugly, but I'd still regard it as shareable, although it may break, e.g. when a column is added to the languages table before the macro-area one ...
It's one of the places in clld apps, where we still have non-cool, technology-dependent URLs.

I though a bit about "proper" macro-area pages (with cool URLs), but I'm not sure they would be as useful (or as much used) as we hope, because they would basically duplicate the information in the filtered languages table; and asking people to bookmark a URL other than the one of the page they are currently on always feels weird (maybe a bit less so, if you ask to bookmark a DOI).
