### ISSUE TITLE
Tibetan divisions

### ISSUE THREAD

**Issue by eroux** [clld/glottolog#308]
I don't know if it's the right place for this kind of request, but there is a comprehensive list of Tibetan dialects / languages in the following article: https://escholarship.org/uc/item/4qd7k36j on the very final page (Appendix C). There is also a map with some coordinates for the dialects on page 47. This seems like a very good source, could the data make it to Glottolog?

**Comment by d97hah** [comment]
Yes and no, the bulk of the list derives from CDTD which last time I
checked is neither published or elsewhere available. It's not great in
principle to have lists which can't be scrutinized. Do you have a copy of
CDTD or know if their dialect list is documented somewhere which is
accessible?

Pada tanggal Sen, 18 Feb 2019 pukul 19.23 Elie Roux <
notifications@github.com> menulis:

**Comment by eroux** [comment]
Well, the volume 2 is available on

https://www.degruyter.com/view/product/465653

at a rather prohibitive price. Fortunately the list of dialects is in the preview pages! I don't have a full version to send you (yet).

In any case, I was wondering if the initially cited article could be used as a primary source?

Best,

**Comment by eroux** [comment]
Can you please contact me by email (I can't have your email address through Github)? (sorry for closing/reopening, pushed the wrong button)

**Comment by d97hah** [comment]
Ok I've managed to download a copy of the CDTD vol 2 which has an inventory
and explanation of the dialects listed, so I'll try to implement that for
Glottolog. The Bialek paper would have been fine to cite for classification
but not for the inventory of dialects because it just lists the names and
refers to something unpublished. But since that CDTD vol 2 is out this is
no longer a problem. all the best, H

Pada tanggal Sen, 18 Feb 2019 pukul 21.47 Elie Roux <
notifications@github.com> menulis:

**Comment by eroux** [comment]
Great, very exciting!

**Comment by eroux** [comment]
thanks, excellent!
