### ISSUE TITLE
Old reference assignments retained across Glottolog versions

### ISSUE THREAD

**Issue by d97hah** [clld/glottolog#348]
It seems old lgcode-tagged references are not deleted when the .bib so changes

For example, this is tagged with Salar [slr] sala1264
https://glottolog.org/resource/reference/id/72394

But the lgcode field does not indicate any relation to Salar [slr] sala1264, but in earlier versions I think it used to (a typo).

**Comment by xrotwang** [comment]
Could be due to the line here:
https://github.com/clld/glottolog/blob/fa9d1ec7c5aac89ac892460848ba9d972d66b69b/languoids/tree/turk1311/comm1245/oghu1243/sala1264/md.ini#L18
Will investigate.

**Comment by xrotwang** [comment]
Ok, so the problem are these non-synchronized source relations in the ini files. AFAIR we introduced these for two reasons:
1. Make the ini files more complete, i.e. allow the user to discover related refs aso from the language info.
2. Provide a separate method to **create** languoid-reference relations.

The problem only comes in because of reason 2, so I'd be inclined to drop this - i.e. **only** create languod-reference relations through `lgcode` fields in bib files, and marking the `[sources]` section in ini files as read-only. I'd still keep the `[sources]` section, but provide a command to synch it with the content in bib files.

This leaves us with the question of what to do with the obsolete sources in ini files. Most of them could be safely removed - but we had a couple which were introduced via the work of Martin's RA in glottologcurator. AFAIR, most have been sources for family nodes. So maybe we add these (any sources for family nodes) into the `lgcode` of the relevant bib entries?

**Comment by xrotwang** [comment]
E.g. the reference https://glottolog.org/resource/reference/id/59200 is related to [volt1241](https://glottolog.org/resource/languoid/id/volt1241) - and I guess rightly so - although there's no corresponding `lgcode` field. Should we add one? There's 1300 such family-level reference relations. Should we add them automatically, or just keep the list as backlog somewhere and work on them on a one-by-one basis?

**Comment by d97hah** [comment]
Thanks Robert! IMHO the best solution seems to be to sync .ini-tags in the
language-level languoids with the lgcode field and leave the .ini-refs for
families (and dialects) as is, so we do not lose the work of Martin's RA.
The family ref tags are no doubt good quality. and so we don't want to do
them on a case-by-case basis.

I don't seem why the family (and-dialect)-level reference tags have to
travel from the .ini:s into the .bib files although I guess that makes the
division of assignment clearer. Mixing glottocodes with the current iso (or
hh)-codes in lgcode might not be ideal from my editing perspective, so if
so I'd vote for a new field "languoids = { ... [], ... []}" where
glottocodes can go.




Pada tanggal Jum, 3 Mei 2019 pukul 10.52 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
But do you think glottocodes as `[abcd1234]` in `lgcode` fields will break code on your side - rather than just not be matched by your `reisobracket` machinery? Even two fields in the same BibTeX record seem like a setup for the next synchronization problem to me.

**Comment by xrotwang** [comment]
Another reason to keep all languoid relations in the bibfiles is that these tend to be less volatile - i.e. are typically append only - as opposed to languoid files, where we'd need machinery to handle the case that a family with sources attached is deleted.

**Comment by d97hah** [comment]
It won't break, it will just look esthetically unpleasing while I edit
(which I agree is not reason enough). So let's do it. Will you get the
pleasure of doing it? Just wait for me to push a new hh.bib just now

Pada tanggal Jum, 3 Mei 2019 pukul 11.38 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
Yeah, my pleasure :)

**Comment by xrotwang** [comment]
@d97hah ok, let me know when I can start.

**Comment by xrotwang** [comment]
ok, this will be repaired in the app at the next release.
