### ISSUE TITLE
Harvest the AUTOTYP references 

### ISSUE THREAD

**Issue by SimonGreenhill** [clld/glottolog#92]
https://github.com/autotyp/autotyp-data/blob/master/bibliography/autotyp.bib

**Comment by xrotwang** [comment]
I guess a (very) large part of these sources will already be covered by either the [Library catalog of Uni Zurich](http://glottolog.org/providers/zurich) or [MPI EVA](http://glottolog.org/providers/mpieva). We should have a look anyway, in particular because explicit links to languages are provided in this bib file.

**Comment by d97hah** [comment]
I am on the case, becuase I am going thru their language:ids at the same
time.

2017-05-29 8:54 GMT+02:00 Robert Forkel <notifications@github.com>:

**Comment by xflr6** [comment]
Fixed in 731e0de2e0e0ff20049ea11a9fd64a70b1a8e2bd
